### ISSUE TITLE
not running

### ISSUE THREAD

**Issue by amigax** [alibenchaabene/OpenAIChatGPTBlazor#1]
doesnt run and says process with an id of 13344 is not running. what am I doing wrong ? :)

**Comment by alibenchaabene** [comment]
This problem seems to be caused by moving a project between workstations, environments, or versions of Visual Studio

Follow steps in my article 

https://medium.com/@alibenchaabene/build-a-chatgpt-client-an-image-generator-in-blazor-using-openai-api-315ce939e8ed
